2023-12-18 12:44:45,094 [ERROR] Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /home/do0236li/miniconda3/envs/py38/lib/python3.9/site-packages/ipykernel/kernelbase.py:285> wait_for=<Future finished result=<Future at 0x...state=pending>> cb=[_chain_future.<locals>._call_set_state() at /home/do0236li/miniconda3/envs/py38/lib/python3.9/asyncio/futures.py:391]>
